runtime: java
env : flex
inbound_services: 
- warmup
derived_file_type:
- java_precompiled

runtime_config: 
  jdk: java17

handlers:
- url: /.*
  script: this field is required, but ignored
skip_files: app.yaml